// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdwczAL6QPnUsNHoOY2IKxc_2B61DSHo',
    appId: '1:879990144728:web:0796b101455935e40221ad',
    messagingSenderId: '879990144728',
    projectId: 'in1soilsensor',
    authDomain: 'in1soilsensor.firebaseapp.com',
    databaseURL: 'https://in1soilsensor-default-rtdb.firebaseio.com',
    storageBucket: 'in1soilsensor.appspot.com',
    measurementId: 'G-9GHZBDDXQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb0g598N0h_VBrf48FYhpdig5rYM_TxjM',
    appId: '1:879990144728:android:b3c807a843989e280221ad',
    messagingSenderId: '879990144728',
    projectId: 'in1soilsensor',
    databaseURL: 'https://in1soilsensor-default-rtdb.firebaseio.com',
    storageBucket: 'in1soilsensor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbqwEnOL7bq3eIF0jHyt3-tdU09_a7fdY',
    appId: '1:879990144728:ios:2c0f4685d6ebfc940221ad',
    messagingSenderId: '879990144728',
    projectId: 'in1soilsensor',
    databaseURL: 'https://in1soilsensor-default-rtdb.firebaseio.com',
    storageBucket: 'in1soilsensor.appspot.com',
    iosClientId: '879990144728-rmshcv74o5r3ug8o8fiatrledjls96t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.soilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbqwEnOL7bq3eIF0jHyt3-tdU09_a7fdY',
    appId: '1:879990144728:ios:1f9f7127b61dc5640221ad',
    messagingSenderId: '879990144728',
    projectId: 'in1soilsensor',
    databaseURL: 'https://in1soilsensor-default-rtdb.firebaseio.com',
    storageBucket: 'in1soilsensor.appspot.com',
    iosClientId: '879990144728-be205pefot6piec2po86k0h0b2ied3uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.soilapp.RunnerTests',
  );
}
